use finances_v1_basic_desenv;


CREATE OR ALTER PROCEDURE CARREGANDO_DADOS_PARA_OLAP 
AS 
BEGIN
    EXECUTE MIGRANDO_TIPO_INVESTIMENTO_OLTP_PARA_OLAP;
	EXECUTE MIGRANDO_USUARIO_OLTP_PARA_OLAP;
	EXECUTE MIGRANDO_CARTEIRA_OLTP_PARA_OLAP;
	EXECUTE MIGRANDO_INVESTIMENTO_OLTP_PARA_OLAP;
	EXECUTE MIGRANDO_RELATORIO_OLTP_PARA_OLAP;
    RETURN 1
END;
