/*EXECUTE CARREGANDO_DADOS_PARA_OLAP
*/

USE finances_v1_basic_desenv;
SELECT * FROM RELATORIO

--CARREGANDO MAIS INFORMAÇOES
EXECUTE CARREGAR_DADOS_EXTERNOS_EXCEL_RELATORIO

---VERIFICANDO SE APLICOU DADOS
SELECT * FROM RELATORIO

---VERIFICANDO SE OS DADOS ATUALIZARAM AUTOMATICO
USE modelo_estrela_desenv
SELECT * FROM RELATORIO